/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Corpus {
    protected boolean swigCMemOwn;
    private long swigCPtr;

    protected Corpus(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public Corpus() {
        this(desrJNI.new_Corpus(), true);
    }

    protected static long getCPtr(Corpus obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    public static Corpus create(Language lang, String inputFormat) {
        long cPtr = desrJNI.Corpus_create__SWIG_0(Language.getCPtr(lang), lang, inputFormat);
        return (cPtr == 0) ? null : new Corpus(cPtr, true);
    }

    public static Corpus create(String lang, String inputFormat) {
        long cPtr = desrJNI.Corpus_create__SWIG_1(lang, inputFormat);
        return (cPtr == 0) ? null : new Corpus(cPtr, true);
    }

    public static Corpus create(String lang) {
        long cPtr = desrJNI.Corpus_create__SWIG_2(lang);
        return (cPtr == 0) ? null : new Corpus(cPtr, true);
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                desrJNI.delete_Corpus(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public SentenceReader sentenceReader(SWIGTYPE_p_std__istream is) {
        long cPtr = desrJNI.Corpus_sentenceReader__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(is));
        return (cPtr == 0) ? null : new SentenceReader(cPtr, true);
    }

    public SentenceReader sentenceReader() {
        long cPtr = desrJNI.Corpus_sentenceReader__SWIG_1(swigCPtr, this);
        return (cPtr == 0) ? null : new SentenceReader(cPtr, true);
    }

    public String toString(Sentence sent) {
        return desrJNI.Corpus_toString(swigCPtr, this, Sentence.getCPtr(sent), sent);
    }

    public AttributeIndex getIndex() {
        long cPtr = desrJNI.Corpus_index_get(swigCPtr, this);
        return (cPtr == 0) ? null : new AttributeIndex(cPtr, false);
    }

    public void setIndex(AttributeIndex value) {
        desrJNI.Corpus_index_set(swigCPtr, this, AttributeIndex.getCPtr(value), value);
    }

}
