/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class EnumeratorToken extends Disposable {
    private long swigCPtr;

    protected EnumeratorToken(long cPtr, boolean cMemoryOwn) {
        super(desrJNI.EnumeratorToken_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(EnumeratorToken obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                desrJNI.delete_EnumeratorToken(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public boolean MoveNext() {
        return desrJNI.EnumeratorToken_MoveNext(swigCPtr, this);
    }

    public Token Current() {
        long cPtr = desrJNI.EnumeratorToken_Current(swigCPtr, this);
        return (cPtr == 0) ? null : new Token(cPtr, false);
    }

    public void Reset() {
        desrJNI.EnumeratorToken_Reset(swigCPtr, this);
    }

    public Token next() {
        long cPtr = desrJNI.EnumeratorToken_next(swigCPtr, this);
        return (cPtr == 0) ? null : new Token(cPtr, true);
    }

    public boolean hasNext() {
        return desrJNI.EnumeratorToken_hasNext(swigCPtr, this);
    }

}
