/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class EnumeratorVectorToken extends Disposable {
    private long swigCPtr;

    protected EnumeratorVectorToken(long cPtr, boolean cMemoryOwn) {
        super(desrJNI.EnumeratorVectorToken_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(EnumeratorVectorToken obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                desrJNI.delete_EnumeratorVectorToken(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public boolean MoveNext() {
        return desrJNI.EnumeratorVectorToken_MoveNext(swigCPtr, this);
    }

    public VectorToken Current() {
        long cPtr = desrJNI.EnumeratorVectorToken_Current(swigCPtr, this);
        return (cPtr == 0) ? null : new VectorToken(cPtr, false);
    }

    public void Reset() {
        desrJNI.EnumeratorVectorToken_Reset(swigCPtr, this);
    }

    public VectorToken next() {
        long cPtr = desrJNI.EnumeratorVectorToken_next(swigCPtr, this);
        return (cPtr == 0) ? null : new VectorToken(cPtr, true);
    }

    public boolean hasNext() {
        return desrJNI.EnumeratorVectorToken_hasNext(swigCPtr, this);
    }

}
