/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class ofstream {
    protected boolean swigCMemOwn;
    private long swigCPtr;

    protected ofstream(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public ofstream(String fn) {
        this(desrJNI.new_ofstream(fn), true);
    }

    protected static long getCPtr(ofstream obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                desrJNI.delete_ofstream(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

}
