/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Sentence extends VectorTreeToken {
    private long swigCPtr;

    protected Sentence(long cPtr, boolean cMemoryOwn) {
        super(desrJNI.Sentence_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    public Sentence(Language language) {
        this(desrJNI.new_Sentence__SWIG_0(Language.getCPtr(language), language), true);
    }

    public Sentence() {
        this(desrJNI.new_Sentence__SWIG_1(), true);
    }

    protected static long getCPtr(Sentence obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                desrJNI.delete_Sentence(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public Language getLanguage() {
        long cPtr = desrJNI.Sentence_language_get(swigCPtr, this);
        return (cPtr == 0) ? null : new Language(cPtr, false);
    }

    public void setLanguage(Language value) {
        desrJNI.Sentence_language_set(swigCPtr, this, Language.getCPtr(value), value);
    }

    public Sentence deref() {
        return new Sentence(desrJNI.Sentence_deref(swigCPtr, this), false);
    }

    public String toString() {
        return desrJNI.Sentence_toString(swigCPtr, this);
    }

}
