/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class VectorToken {
    protected boolean swigCMemOwn;
    private long swigCPtr;

    protected VectorToken(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public VectorToken() {
        this(desrJNI.new_VectorToken__SWIG_0(), true);
    }

    public VectorToken(long n) {
        this(desrJNI.new_VectorToken__SWIG_1(n), true);
    }

    protected static long getCPtr(VectorToken obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                desrJNI.delete_VectorToken(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public long size() {
        return desrJNI.VectorToken_size(swigCPtr, this);
    }

    public long capacity() {
        return desrJNI.VectorToken_capacity(swigCPtr, this);
    }

    public void reserve(long n) {
        desrJNI.VectorToken_reserve(swigCPtr, this, n);
    }

    public boolean isEmpty() {
        return desrJNI.VectorToken_isEmpty(swigCPtr, this);
    }

    public void clear() {
        desrJNI.VectorToken_clear(swigCPtr, this);
    }

    public void add(Token x) {
        desrJNI.VectorToken_add(swigCPtr, this, Token.getCPtr(x), x);
    }

    public Token get(int i) {
        long cPtr = desrJNI.VectorToken_get(swigCPtr, this, i);
        return (cPtr == 0) ? null : new Token(cPtr, false);
    }

    public void set(int i, Token val) {
        desrJNI.VectorToken_set(swigCPtr, this, i, Token.getCPtr(val), val);
    }

    public String toString() {
        return desrJNI.VectorToken_toString(swigCPtr, this);
    }

}
